name: weavershub
description: "Weavers hub mobile application"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  get:
  firebase_core:
  firebase_auth:
  firebase_cloud_firestore:
  image_picker:
  firebase_storage:
  firebase_database:
  provider:
  timeago:
  cached_network_image:
  pay_with_paystack:
  http:
  intl:
  firebase_messaging: ^14.6.2
  flutter_local_notifications: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
     - assets/
  #   - images/a_dot_ham.jpeg


